# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-Next-OO
version:      0.03
version_from: lib/File/Next/OO.pm
installdirs:  site
requires:
    File::Next:                    0.28
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
